// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomIntentIR } from "./CustomIntentIR";
import type { HelperIR } from "./HelperIR";
import type { JsonValue } from "./JsonValue";
import type { ModelConfigBlockIR } from "./ModelConfigBlockIR";
import type { ToolIR } from "./ToolIR";
import type { TypeDeclIR } from "./TypeDeclIR";
import type { WorkflowIR } from "./WorkflowIR";

/**
 * Root IR for a compiled `.agent` file. Mirrors `ir-runtime/src/types.rs::AgentIR`.
 */
export type AgentIR = { name: string, modelConfig: Array<ModelConfigBlockIR>, input: JsonValue | null, output: JsonValue | null, context: JsonValue | null, tools: Array<ToolIR>, workflows: Array<WorkflowIR>, helpers: Array<HelperIR>, types: { [key in string]?: TypeDeclIR } | null, 
/**
 * Tool grants per helper: `"all"` or `["toolA", "toolB"]`.
 */
helperToolGrants: { [key in string]?: JsonValue } | null, 
/**
 * Handoff string per helper: `"user"` | `"thenContinue"` | absent → Return.
 */
helperHandoff: { [key in string]?: string } | null, tests: Array<JsonValue>, 
/**
 * Lifecycle config (maxTokens, maxMessages, etc.).
 */
lifecycle: JsonValue | null, 
/**
 * Custom intent declarations for this agent.
 */
customIntents: Array<CustomIntentIR> | null, };
