// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomIntentIR } from "./CustomIntentIR";
import type { JsonValue } from "./JsonValue";
import type { ModelConfigBlockIR } from "./ModelConfigBlockIR";
import type { ToolIR } from "./ToolIR";
import type { WorkflowIR } from "./WorkflowIR";

/**
 * Mirrors `ir-runtime/src/types.rs::Helper`.
 */
export type HelperIR = { name: string, description: string | null, modelConfig: Array<ModelConfigBlockIR>, input: JsonValue | null, output: JsonValue | null, context: JsonValue | null, tools: Array<ToolIR>, workflows: Array<WorkflowIR>, customIntents: Array<CustomIntentIR> | null, examples: Array<JsonValue>, };
