// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";
import type { ModelProviderIR } from "./ModelProviderIR";

/**
 * Mirrors `ir-runtime::ModelConfig`.
 */
export type ModelConfigIR = { model: ModelProviderIR, embedding: ModelProviderIR | null, prompt: JsonValue, };
