[package]
name = "auwgent-sdk-rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "auwgent_sdk_rust"

[dependencies]
auwgent-bridge = { path = "../../runtime/crates/auwgent-bridge" }
auwgent-drivers = { path = "../../runtime/crates/auwgent-drivers" }
auwgent-engine = { path = "../../runtime/crates/auwgent-engine" }
auwgent-ir-schema = { path = "../../auwgent-compiler/crates/auwgent-ir-schema" }
auwgent-middleware = { path = "../../runtime/crates/auwgent-middleware" }
auwgent-runtime-core = { path = "../../runtime/crates/auwgent-runtime-core" }
auwgent-session = { path = "../../runtime/crates/auwgent-session" }
async-trait = "0.1"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
members = [".", "rust-verfication"]
resolver = "2"
