// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionIR } from "./ExpressionIR";

/**
 * Mirrors `ir-runtime::Comparison`.
 */
export type ComparisonIR = { left: ExpressionIR, operator: string, right: ExpressionIR, };
