// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonIR } from "./ComparisonIR";
import type { ExpressionIR } from "./ExpressionIR";

/**
 * Mirrors `ir-runtime::Condition`.
 */
export type ConditionIR = { "type": "comparison" } & ComparisonIR | { "type": "boolean", value: ExpressionIR, } | { "type": "contextRef", property: string, } | { "type": "logical", op: string, left: ConditionIR, right: ConditionIR, };
