// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * Mirrors `ir-runtime::CustomIntentDef`.
 */
export type CustomIntentIR = { name: string, description: string | null, 
/**
 * Intent fields as a property map JSON object.
 */
fields: JsonValue, examples: Array<JsonValue>, };
