// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Prompt conversation example pair. Mirrors `ir-runtime::ExamplePair`.
 */
export type ExamplePairIR = { user: string, assistant: string, };
