// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three handoff modes a helper can operate in.
 *
 * Serialized to/from the JSON `helperHandoff` map value:
 * - `Return` → absent (no entry in the map)
 * - `User` → `"user"`
 * - `ThenContinue` → `"thenContinue"`
 *
 * Mirrors `ir-runtime/src/runtime/helper_runner.rs::HandoffMode`.
 */
export type HandoffKindIR = "return" | "user" | "thenContinue";
