// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transparent wrapper around `serde_json::Value` that implements `ts_rs::TS`
 * mapping natively to TypeScript's `any` and Python's `Any`.
 */
export type JsonValue = any;
