// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelConfigIR } from "./ModelConfigIR";
import type { NamedModelConfigIR } from "./NamedModelConfigIR";

/**
 * Mirrors `ir-runtime::ModelConfigEntry`.
 */
export type ModelConfigBlockIR = { defaultConfig: ModelConfigIR | null, namedConfig: Array<NamedModelConfigIR> | null, };
