// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * Mirrors `ir-runtime::ModelProvider`.
 */
export type ModelProviderIR = { "type": "gemini", modelName: string, config: JsonValue | null, } | { "type": "openai", modelName: string, config: JsonValue | null, } | { "type": "custom", id: string, url: string, modelName: string, config: JsonValue | null, } | { "type": "modelRef", name: string, };
