// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * Mirrors `ir-runtime/src/types.rs::Tool`.
 */
export type ToolIR = { name: string, description: string | null, 
/**
 * Parameter map: param name → type field JSON.
 */
params: JsonValue, returns: JsonValue, examples: Array<JsonValue>, };
