// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * Mirrors `ir-runtime/src/types.rs::TypeProperty`.
 */
export type TypePropertyIR = { type: JsonValue, optional: boolean, description: string | null, };
