// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypePropertyIR } from "./TypePropertyIR";

/**
 * Mirrors `ir-runtime/src/types.rs::TypeDefinition`.
 */
export type TypeDeclIR = { isOutput: boolean, properties: { [key in string]?: TypePropertyIR }, };
