// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionIR } from "./ExpressionIR";
import type { JsonValue } from "./JsonValue";
import type { ToolIR } from "./ToolIR";

/**
 * Mirrors `ir-runtime/src/types.rs::Workflow`.
 */
export type WorkflowIR = { 
/**
 * Serialized as `flowName`.
 */
flowName: string, 
/**
 * Serialized as `flowParams`.
 */
flowParams: JsonValue, returns: JsonValue, description: string | null, body: Array<ExpressionIR>, tools: Array<ToolIR>, examples: Array<JsonValue>, };
