/**
 * @auwgent/runtime — Type-Safe TypeScript Wrapper
 *
 * This module provides a type-safe layer on top of the native Rust binding.
 * It extracts tool names from the IR JSON at the TYPE level, so TypeScript
 * will error if you forget to register any tool the agent needs.
 *
 * Usage:
 * ```ts
 * import { createAuwgent } from '@auwgent/runtime';
 *
 * const ir = JSON.parse(fs.readFileSync('main.agent.json', 'utf8'));
 *
 * const agent = createAuwgent(ir, {
 *   tools: {
 *     hello: async (args) => ({ message: `Hello ${args.id}` }),
 *   },
 *   apiKeys: { geminiApiKey: process.env.GEMINI_API_KEY },
 * });
 *
 * // Observe intents in real-time
 * agent.onIntent((name, value) => {
 *   console.log(`[${name}]`, value);
 * });
 *
 * const session = await agent.run('Call the hello tool with id abc');
 * ```
 */

// ── Native binding (generated by napi-rs build) ──────────────────────────
import { Auwgent as AuwgentNative } from './index.js';

// Re-export the native class for advanced users who want raw access
export { AuwgentNative };

// ── Type-Level IR Tool Extraction ────────────────────────────────────────

/** Minimal shape of a tool definition in the Agent IR */
export interface IRToolDef {
    name: string;
    description?: string;
    params: unknown;
    returns: unknown;
}

export interface IRModelProvider {
    type: string;
}

export interface IRModelConfig {
    model?: IRModelProvider;
}

export interface IRNamedModelConfig {
    model?: IRModelProvider;
}

export interface IRModelConfigEntry {
    defaultConfig?: IRModelConfig;
    namedConfig?: IRNamedModelConfig[] | null;
}

export interface IRHelperShape {
    modelConfig?: IRModelConfigEntry[] | null;
}

/** Minimal shape of an Agent IR document (only the fields we need) */
export interface AgentIRShape {
    name: string;
    tools: readonly IRToolDef[];
    modelConfig?: IRModelConfigEntry[];
    helpers?: readonly IRHelperShape[];
    [key: string]: unknown;
}

/**
 * Extract tool names from an IR object as a union type.
 *
 * Given `{ tools: [{ name: 'hello' }, { name: 'search' }] }`,
 * this produces `'hello' | 'search'`.
 */
export type ExtractToolNames<IR extends AgentIRShape> =
    IR['tools'][number]['name'];

/**
 * A record requiring an async implementation for every tool in the IR.
 * TypeScript will error if any tool is missing.
 */
export type ToolRegistry<IR extends AgentIRShape> = {
    [K in ExtractToolNames<IR>]: (args: Record<string, unknown>) => Promise<unknown>;
};

export type ApiKeys = {
    geminiApiKey?: string;
    openaiApiKey?: string;
    customApiKey?: string;
    customUrl?: string;
};

function collectRequiredProviders(ir: AgentIRShape): Set<string> {
    const providers = new Set<string>();
    const addProvider = (value?: string) => {
        if (value) {
            providers.add(value.toLowerCase());
        }
    };
    const addFromEntries = (entries?: IRModelConfigEntry[] | null) => {
        if (!entries) {
            return;
        }
        for (const entry of entries) {
            addProvider(entry.defaultConfig?.model?.type);
            if (entry.namedConfig) {
                for (const named of entry.namedConfig) {
                    addProvider(named.model?.type);
                }
            }
        }
    };

    addFromEntries(ir.modelConfig);
    if (ir.helpers) {
        for (const helper of ir.helpers) {
            addFromEntries(helper.modelConfig);
        }
    }

    return providers;
}

// ── Intent Types ─────────────────────────────────────────────────────────

/**
 * Control signal returned by an intent handler.
 * - `undefined` / `null` → engine auto-executes (default behavior)
 * - `{ skip: true }` → skip this tool/workflow call
 * - `{ result: value }` → use this result instead of executing
 */
export type IntentControl =
    | { skip: true }
    | { result: unknown }
    | void
    | null
    | undefined;

/**
 * Intent handler callback.
 *
 * Receives the intent name and parsed value from the LLM's output:
 * - `"tool_call"` → `{ type: "toolName", args: {...} }`
 * - `"tool_result"` → `{ name: "toolName", result: {...} }`
 * - `"response_text"` → `{ text: "..." }`
 * - `"response_schema"` → structured output matching your output type
 * - `"workflow_call"` → `{ type: "wfName", args: {...} }`
 * - `"error"` → `{ source: "...", message: "..." }`
 * - Custom intents → as defined by the DSL
 */
export type IntentHandler = (
    name: string,
    value: unknown,
) => IntentControl | Promise<IntentControl>;

/**
 * Partial intent handler — fires as YAML data streams in.
 * Observational only, no return value needed.
 */
export type PartialIntentHandler = (name: string, value: unknown) => void;

// ── Configuration ────────────────────────────────────────────────────────

export interface AuwgentConfig<IR extends AgentIRShape> {
    tools: ToolRegistry<IR>;
    context?: Record<string, unknown>;
    apiKeys?: ApiKeys;
    geminiApiKey?: string;
}

// ── Session Types ────────────────────────────────────────────────────────

export type Role = 'system' | 'user' | 'model' | 'toolResult';

export interface Message {
    role: Role;
    content: string;
}

export interface Turn {
    input: string;
    modelResponse: string;
}

export interface SessionState {
    systemPrompt?: string;
    turns: Turn[];
}

// ── Type-Safe Auwgent Wrapper ────────────────────────────────────────────

export class TypedAuwgent<IR extends AgentIRShape> {
    private native: InstanceType<typeof AuwgentNative>;
    private ir: IR;

    constructor(ir: IR, config: AuwgentConfig<IR>) {
        this.ir = ir;
        this.native = new AuwgentNative(JSON.stringify(ir));

        if (config.context) {
            this.native.setContext(config.context);
        }

        const requiredProviders = collectRequiredProviders(ir);
        const apiKeys = config.apiKeys ?? (config.geminiApiKey ? { geminiApiKey: config.geminiApiKey } : undefined);
        const shouldSetGemini =
            apiKeys?.geminiApiKey &&
            (requiredProviders.size === 0 || requiredProviders.has('gemini'));
        if (shouldSetGemini) {
            this.native.setGeminiDriver(apiKeys.geminiApiKey!);
        }

        // Register all tools — guaranteed complete by the type system
        for (const [name, handler] of Object.entries(config.tools)) {
            this.native.registerTool(name, handler as (args: any) => Promise<any>);
        }
    }

    /**
     * Register an intent callback for real-time streaming events.
     *
     * The engine auto-executes tools/workflows by default. This callback
     * lets you observe what's happening (for UI) and optionally control it.
     *
     * @example
     * ```ts
     * // Observe all intents
     * agent.onIntent((name, value) => {
     *   console.log(`[${name}]`, value);
     * });
     *
     * // Control specific intents
     * agent.onIntent(async (name, value) => {
     *   if (name === 'tool_call' && value.type === 'deleteFile') {
     *     const ok = await confirm('Delete file?');
     *     if (!ok) return { skip: true };
     *   }
     * });
     * ```
     */
    onIntent(handler: IntentHandler): void {
        this.native.onIntent(async (name: string, value: unknown) => {
            return handler(name, value);
        });
    }

    /**
     * Register a partial intent callback for streaming updates.
     *
     * Fires as YAML data streams in, BEFORE the intent block is complete.
     * Useful for streaming text to the UI token-by-token or showing
     * tool call args as they arrive.
     *
     * Observational only — no control/skip/override.
     *
     * @example
     * ```ts
     * agent.onIntentPartial((name, value) => {
     *   if (name === 'response_text') {
     *     process.stdout.write(value.text ?? '');
     *   }
     * });
     * ```
     */
    onIntentPartial(handler: PartialIntentHandler): void {
        this.native.onIntentPartial((name: string, value: unknown) => {
            handler(name, value);
        });
    }

    /** Run the agentic loop. Returns the exported session state. */
    async run(input?: string): Promise<SessionState> {
        const json = await this.native.run(input ?? null);
        return JSON.parse(json) as SessionState;
    }

    /** Export session state for persistence. */
    exportSession(): SessionState {
        return JSON.parse(this.native.exportSession()) as SessionState;
    }

    /** Import a previously exported session state. */
    importSession(session: SessionState): void {
        this.native.importSession(JSON.stringify(session));
    }

    /** Clear the session (fresh conversation). */
    clearSession(): void {
        this.native.clearSession();
    }

    /** Generate the system prompt (debugging). */
    generatePrompt(): string {
        return this.native.generatePrompt();
    }

    /** Get tool names defined in the IR. */
    getToolNames(): ExtractToolNames<IR>[] {
        return this.native.getToolNames() as ExtractToolNames<IR>[];
    }

    /** Get tool schemas (for introspection). */
    getToolSchemas(): IRToolDef[] {
        return JSON.parse(this.native.getToolSchemas()) as IRToolDef[];
    }

    /** Access the raw native binding for advanced usage. */
    get raw(): InstanceType<typeof AuwgentNative> {
        return this.native;
    }
}

// ── Factory Function ─────────────────────────────────────────────────────

/**
 * Create a type-safe Auwgent agent from an IR object.
 *
 * The IR object MUST be typed with `as const` for full type inference:
 * ```ts
 * const ir = JSON.parse(fs.readFileSync('main.agent.json', 'utf8')) as const;
 * const agent = createAuwgent(ir, { tools: { ... } });
 * ```
 *
 * @param ir - The Agent IR object (parsed from JSON)
 * @param config - Config with tools and optional API key
 * @returns A type-safe Auwgent instance
 */
export function createAuwgent<const IR extends AgentIRShape>(
    ir: IR,
    config: AuwgentConfig<IR>,
): TypedAuwgent<IR> {
    return new TypedAuwgent(ir, config);
}

export function createAuwgentFromIRJson<const IR extends AgentIRShape>(
    irJson: string,
    config: AuwgentConfig<IR>,
): TypedAuwgent<IR> {
    const ir = JSON.parse(irJson) as IR;
    return new TypedAuwgent(ir, config);
}

// ── Helper: Load IR with type inference ──────────────────────────────────

/**
 * Parse an IR JSON string into a typed IR object.
 * Use with `as const` for full tool name inference.
 */
export function parseIR<const IR extends AgentIRShape>(json: string): IR {
    return JSON.parse(json) as IR;
}
