/**
 * @auwgent/runtime — Type-Safe TypeScript Wrapper
 *
 * This module provides a type-safe layer on top of the native Rust binding.
 * It extracts tool names from the IR JSON at the TYPE level, so TypeScript
 * will error if you forget to register any tool the agent needs.
 *
 * Usage:
 * ```ts
 * import { createAuwgent, type InferTools } from '@auwgent/runtime';
 *
 * const ir = JSON.parse(fs.readFileSync('main.agent.json', 'utf8'));
 *
 * const agent = createAuwgent(ir, {
 *   tools: {
 *     hello: async (args) => ({ message: `Hello ${args.id}` }),
 *     // TS will error if you miss any tool defined in the IR
 *   },
 *   geminiApiKey: process.env.GEMINI_API_KEY,
 * });
 *
 * const session = await agent.run('Call the hello tool with id abc');
 * ```
 */

// ── Native binding (generated by napi-rs build) ──────────────────────────
// The generated index.js handles platform detection and .node loading
// The generated index.d.ts provides the type declarations
import { Auwgent as AuwgentNative } from './index.js';

// Re-export the native class for advanced users who want raw access
export { AuwgentNative };

// ── Type-Level IR Tool Extraction ────────────────────────────────────────

/** Minimal shape of a tool definition in the Agent IR */
export interface IRToolDef {
    name: string;
    description?: string;
    params: Record<string, unknown>;
    returns: Record<string, unknown>;
}

/** Minimal shape of an Agent IR document (only the fields we need) */
export interface AgentIRShape {
    name: string;
    tools: readonly IRToolDef[];
    [key: string]: unknown;
}

/**
 * Extract tool names from an IR object as a union type.
 *
 * Given `{ tools: [{ name: 'hello' }, { name: 'search' }] }`,
 * this produces `'hello' | 'search'`.
 */
export type ExtractToolNames<IR extends AgentIRShape> =
    IR['tools'][number]['name'];

/**
 * A record requiring an async implementation for every tool in the IR.
 * TypeScript will error if any tool is missing.
 */
export type ToolRegistry<IR extends AgentIRShape> = {
    [K in ExtractToolNames<IR>]: (args: Record<string, unknown>) => Promise<unknown>;
};

// ── Configuration ────────────────────────────────────────────────────────

export interface AuwgentConfig<IR extends AgentIRShape> {
    /** Implementation for every tool defined in the IR — TS enforces completeness */
    tools: ToolRegistry<IR>;
    /** Gemini API key (creates the GeminiDriver automatically) */
    geminiApiKey?: string;
}

// ── Session Types ────────────────────────────────────────────────────────

export type Role = 'system' | 'user' | 'model' | 'toolResult';

export interface Message {
    role: Role;
    content: string;
}

export interface Turn {
    input: string;
    modelResponse: string;
    steps: RunStep[];
}

export type RunStep =
    | { type: 'prompt'; content: string }
    | { type: 'modelResponse'; content: string }
    | { type: 'modelOutput'; text?: string; rawYaml?: string }
    | { type: 'intentAction'; name: string; args: unknown; result?: unknown }
    | { type: 'error'; message: string };

export interface SessionState {
    systemPrompt?: string;
    turns: Turn[];
    steps: RunStep[];
}

// ── Type-Safe Auwgent Wrapper ────────────────────────────────────────────

export class TypedAuwgent<IR extends AgentIRShape> {
    private native: InstanceType<typeof AuwgentNative>;
    private ir: IR;

    constructor(ir: IR, config: AuwgentConfig<IR>) {
        this.ir = ir;
        this.native = new AuwgentNative(JSON.stringify(ir));

        // Set driver if API key provided
        if (config.geminiApiKey) {
            this.native.setGeminiDriver(config.geminiApiKey);
        }

        // Register all tools — guaranteed complete by the type system
        for (const [name, handler] of Object.entries(config.tools)) {
            this.native.registerTool(name, handler as (args: any) => Promise<any>);
        }
    }

    /** Run the agentic loop. Returns the exported session state. */
    async run(input?: string): Promise<SessionState> {
        const json = await this.native.run(input ?? null);
        return JSON.parse(json) as SessionState;
    }

    /** Export session state for persistence. */
    exportSession(): SessionState {
        return JSON.parse(this.native.exportSession()) as SessionState;
    }

    /** Import a previously exported session state. */
    importSession(session: SessionState): void {
        this.native.importSession(JSON.stringify(session));
    }

    /** Clear the session (fresh conversation). */
    clearSession(): void {
        this.native.clearSession();
    }

    /** Generate the system prompt (debugging). */
    generatePrompt(): string {
        return this.native.generatePrompt();
    }

    /** Get tool names defined in the IR. */
    getToolNames(): ExtractToolNames<IR>[] {
        return this.native.getToolNames() as ExtractToolNames<IR>[];
    }

    /** Get tool schemas (for introspection). */
    getToolSchemas(): IRToolDef[] {
        return JSON.parse(this.native.getToolSchemas()) as IRToolDef[];
    }

    /** Get session steps (debugging). */
    getSessionSteps(): RunStep[] {
        return JSON.parse(this.native.getSessionSteps()) as RunStep[];
    }

    /** Access the raw native binding for advanced usage. */
    get raw(): InstanceType<typeof AuwgentNative> {
        return this.native;
    }
}

// ── Factory Function ─────────────────────────────────────────────────────

/**
 * Create a type-safe Auwgent agent from an IR object.
 *
 * The IR object MUST be typed with `as const` for full type inference:
 * ```ts
 * const ir = JSON.parse(fs.readFileSync('main.agent.json', 'utf8')) as const;
 * const agent = createAuwgent(ir, { tools: { ... } });
 * ```
 *
 * @param ir - The Agent IR object (parsed from JSON)
 * @param config - Config with tools and optional API key
 * @returns A type-safe Auwgent instance
 */
export function createAuwgent<const IR extends AgentIRShape>(
    ir: IR,
    config: AuwgentConfig<IR>,
): TypedAuwgent<IR> {
    return new TypedAuwgent(ir, config);
}

// ── Helper: Load IR with type inference ──────────────────────────────────

/**
 * Parse an IR JSON string into a typed IR object.
 * Use with `as const` for full tool name inference.
 */
export function parseIR<const IR extends AgentIRShape>(json: string): IR {
    return JSON.parse(json) as IR;
}
