/**
 * @auwgent/runtime — Type-Safe TypeScript Wrapper
 *
 * This module provides a type-safe layer on top of the native Rust binding.
 * It extracts tool names from the IR JSON at the TYPE level, so TypeScript
 * will error if you forget to register any tool the agent needs.
 */

// ── Native binding (generated by napi-rs build) ──────────────────────────
import { Auwgent as AuwgentNative } from './index.js';

// Re-export the native class for advanced users who want raw access
export { AuwgentNative };

import type {
    AgentIRShape,
    ToolRegistry,
    ApiKeys,
    IRModelConfigEntry,
    ExtractToolNames,
    IRToolDef,
    IntentHandler,
    IntentHandlers,
    PartialIntentHandler,
    PartialIntentHandlers,
    SessionState
} from './types.js';

import type { Middleware, MiddlewareContext } from './middleware.js';

export * from './types.js';
export * from './middleware.js';

function collectRequiredProviders(ir: AgentIRShape): Set<string> {
    const providers = new Set<string>();
    const addProvider = (value?: string) => {
        if (value) {
            providers.add(value.toLowerCase());
        }
    };
    const addFromEntries = (entries?: IRModelConfigEntry[] | null) => {
        if (!entries) {
            return;
        }
        for (const entry of entries) {
            addProvider(entry.defaultConfig?.model?.type);
            if (entry.namedConfig) {
                for (const named of entry.namedConfig) {
                    addProvider(named.model?.type);
                }
            }
        }
    };

    addFromEntries(ir.modelConfig);
    if (ir.helpers) {
        for (const helper of ir.helpers) {
            addFromEntries(helper.modelConfig as IRModelConfigEntry[]);
        }
    }

    return providers;
}

// ── Configuration ────────────────────────────────────────────────────────

export interface AuwgentConfig<IR extends AgentIRShape> {
    tools: ToolRegistry<IR>;
    middleware?: Middleware<IR>[];
    context?: Record<string, unknown>;
    apiKeys: ApiKeys<IR>;
}

// ── Type-Safe Auwgent Wrapper ────────────────────────────────────────────

export class TypedAuwgent<
    IR extends AgentIRShape,
    CustomIntents = never,
    Output = IR['output'] extends null ? any : IR['output'],
    Tools = ToolRegistry<IR>
> {
    private native: InstanceType<typeof AuwgentNative>;
    private ir: IR;
    private middleware: Middleware<IR, CustomIntents, Output, Tools>[];

    // ── Deferred intent handler storage ──
    // We store the user's handler here instead of immediately registering
    // it with the native binding. This allows us to register/deregister
    // the ThreadSafeFunction around each `run()` call, preventing the
    // N-API TSFN from keeping the Node.js event loop alive forever.
    private storedIntentHandler: IntentHandler<IR, CustomIntents, Output, Tools> | null = null;
    private storedPartialHandler: PartialIntentHandler<IR, CustomIntents, Output, Tools> | null = null;

    constructor(ir: IR, config: AuwgentConfig<IR>) {
        this.ir = ir;
        this.middleware = (config.middleware as any) || [];
        this.native = new AuwgentNative(JSON.stringify(ir));

        if (config.context) {
            this.native.setContext(config.context);
        }

        const apiKeys = config.apiKeys as Record<string, string | undefined>;

        if (apiKeys?.geminiApiKey) {
            this.native.setGeminiDriver(apiKeys.geminiApiKey);
        }

        if (apiKeys?.openaiApiKey) {
            this.native.setOpenaiDriver(apiKeys.openaiApiKey);
        }

        // Register all tools — guaranteed complete by the type system
        for (const [name, handler] of Object.entries(config.tools)) {
            this.native.registerTool(name, handler as (args: any) => Promise<any>);
        }
    }

    /**
     * Register an intent callback for real-time streaming events.
     * The handler is stored and automatically registered/deregistered
     * around each `run()` call so the process can exit cleanly.
     */
    onIntent(handler: IntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedIntentHandler = handler;
    }

    /**
     * Register multiple intent handlers using an object-style API.
     */
    onHandlers(handlers: IntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntent(async (...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) return await (h as any)(value);
        });
    }

    /**
     * Register a partial intent callback for streaming updates.
     */
    onIntentPartial(handler: PartialIntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedPartialHandler = handler;
    }

    onHandlersPartial(handlers: PartialIntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntentPartial((...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) (h as any)(value);
        });
    }

    // Shared context storage for cross-hook state mapping
    private sharedContext: MiddlewareContext = {};

    /**
     * Activate the native ThreadSafeFunction listeners just before run().
     * This binds the stored handlers (including middleware pipeline) to the
     * Rust engine. After run() completes, `deactivateListeners()` replaces
     * them with no-ops so the TSFN ref is released and Node can exit.
     */
    private activateListeners(): void {
        const userHandler = this.storedIntentHandler;

        // Always register an onIntent callback (even if user didn't provide one)
        // so middleware can still intercept intents.
        this.native.onIntent(async (name: string, value: any) => {
            const intentCtx: MiddlewareContext = { ...this.sharedContext };

            // Extract _raw from Rust-injected field and move to ctx.rawBlock
            // This keeps intent values clean and typed for the user,
            // while making raw YAML available to middleware for logging/audit
            if (value && typeof value === 'object' && '_raw' in value) {
                intentCtx.rawBlock = value._raw;
                delete value._raw;
            }

            // Pipeline through middleware
            for (const m of this.middleware) {
                if (m.onIntent) {
                    try {
                        const control = await (m.onIntent as any)(name, value, intentCtx);
                        if (control !== undefined && control !== null) {
                            return control as any;
                        }
                    } catch (e) {
                        throw e;
                    }
                }
            }

            // Forward to user handler
            if (userHandler) {
                return (userHandler as any)(name, value);
            }
        });

        // Register partial handler if provided
        if (this.storedPartialHandler) {
            const partialHandler = this.storedPartialHandler;
            this.native.onIntentPartial((name: string, value: any) => {
                (partialHandler as any)(name, value);
            });
        }
    }

    /**
     * Replace the native listeners with no-ops to release the TSFN ref.
     * This allows the Node.js event loop to drain and the process to exit.
     */
    private deactivateListeners(): void {
        // Replace with no-op callbacks — this causes the Rust engine to drop
        // the old Arc<ThreadsafeFunction>, which releases the libuv ref.
        this.native.onIntent(() => undefined);
        this.native.onIntentPartial(() => { });
    }

    /** Run the agentic loop. Returns the exported session state. */
    async run(input?: string): Promise<SessionState> {
        this.sharedContext = {}; // Clear context for new run
        let currentSession = this.exportSession();

        if (input) {
            currentSession.turns.push({ input, model_response: "" });
        }

        // Activate listeners just-in-time before running
        this.activateListeners();

        try {
            // onRunStart Interception
            for (const m of this.middleware) {
                if (m.onRunStart) {
                    currentSession = await m.onRunStart(currentSession, this.sharedContext);
                }
            }

            // Execute Native
            this.importSession(currentSession);
            const json = await this.native.run(input ? null : (input ?? null));
            currentSession = JSON.parse(json) as SessionState;

            // onRunComplete Interception
            for (const m of this.middleware) {
                if (m.onRunComplete) {
                    await m.onRunComplete(currentSession, this.sharedContext);
                }
            }

            return currentSession;

        } catch (error) {
            let handled = false;
            for (const m of this.middleware) {
                if (m.onError) {
                    const shouldSwallow = await m.onError(error as Error, currentSession, this.sharedContext);
                    if (shouldSwallow) {
                        handled = true;
                        break;
                    }
                }
            }
            if (!handled) {
                throw error;
            }
            return currentSession;
        } finally {
            // Deactivate listeners after run to release the TSFN ref
            // and allow the Node.js process to exit gracefully.
            this.deactivateListeners();
        }
    }

    /** Export session state for persistence. */
    exportSession(): SessionState {
        return JSON.parse(this.native.exportSession()) as SessionState;
    }

    /** Import a previously exported session state. */
    importSession(session: SessionState): void {
        this.native.importSession(JSON.stringify(session));
    }

    /** Clear the session (fresh conversation). */
    clearSession(): void {
        this.native.clearSession();
    }

    /** Generate the system prompt (debugging). */
    generatePrompt(): string {
        return this.native.generatePrompt();
    }

    /** Get tool names defined in the IR. */
    getToolNames(): ExtractToolNames<IR>[] {
        return this.native.getToolNames() as ExtractToolNames<IR>[];
    }

    /** Get tool schemas (for introspection). */
    getToolSchemas(): IRToolDef[] {
        return JSON.parse(this.native.getToolSchemas()) as IRToolDef[];
    }

    /** Access the raw native binding for advanced usage. */
    get raw(): InstanceType<typeof AuwgentNative> {
        return this.native;
    }
}

// ── Factory Function ─────────────────────────────────────────────────────

/**
 * Create a type-safe Auwgent agent from an IR object.
 */
export function createAuwgent<
    const IR extends AgentIRShape,
    CustomIntents = never,
    Output = any,
    Tools extends Record<string, any> = ToolRegistry<IR>
>(
    ir: IR,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function createAuwgentFromIRJson<
    const IR extends AgentIRShape,
    CustomIntents = never,
    Output = IR['output'] extends null ? any : IR['output'],
    Tools = ToolRegistry<IR>
>(
    irJson: string,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    const ir = JSON.parse(irJson) as IR;
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function parseIR<const IR extends AgentIRShape>(json: string): IR {
    return JSON.parse(json) as IR;
}
