/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Auwgent {
  /**
   * Create an Auwgent engine from a JSON IR string.
   *
   * ```js
   * const agent = new Auwgent(fs.readFileSync('main.agent.json', 'utf8'));
   * ```
   */
  constructor(irJson: string)
  /** Set the Gemini driver with the given API key. */
  setGeminiDriver(apiKey: string): void
  /**
   * Register a tool by name. The callback receives a JSON args object
   * and must return a JSON result.
   *
   * ```js
   * agent.registerTool('search', async (args) => {
   *   const result = await search(args.query);
   *   return { results: result };
   * });
   * ```
   */
  registerTool(name: string, callback: (args: any) => Promise<any>): void
  /**
   * Run the agentic loop with the given input.
   * Returns the exported session state as JSON.
   *
   * ```js
   * const session = await agent.run('Hello, agent!');
   * ```
   */
  run(input?: string | undefined | null): Promise<string>
  /**
   * Export the current session state as a JSON string.
   * The host can persist this and restore it later with `importSession()`.
   */
  exportSession(): string
  /** Import a previously exported session state. */
  importSession(json: string): void
  /** Clear the session (start a fresh conversation). */
  clearSession(): void
  /** Generate the system prompt (useful for debugging). */
  generatePrompt(): string
  /**
   * Get all tool names defined in the IR.
   * Used by the TypeScript wrapper for type-safe tool registration.
   */
  getToolNames(): Array<string>
  /** Get tool schemas as JSON (for TypeScript type generation). */
  getToolSchemas(): string
  /** Get the final session steps (for debugging). */
  getSessionSteps(): string
  /** Write a chunk directly to the orchestrator (for simulation/testing). */
  writeChunk(chunk: string): void
  /** Finalize the LLM stream (for simulation/testing). */
  endStream(): string
  /** Process any pending intents (for simulation/testing). */
  processIntents(): Promise<string>
}
