[package]
name = "auwgent-pyo3"
version = "0.1.0"
edition = "2024"

[lib]
name = "_auwgent_sdk"
crate-type = ["cdylib"]

[dependencies]
ir-runtime = { path = "../../ir-runtime" }
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38", "generate-import-lib"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime", "attributes"] }
tokio = { version = "1.43", features = ["full", "rt", "macros"] }
serde_json = "1.0"
futures-util = "0.3"

