//! # auwgent-ir-schema
//!
//! Typed Rust structs representing the Auwgent IR (Intermediate Representation)
//! serialized into `.agent.json` files.
//!
//! These structs are the **single source of truth** for:
//! - The `.agent.json` format (via `serde`)
//! - TypeScript type stubs in the TS SDK (via `ts-rs` — see `build.rs`)
//! - Python TypedDicts in the Python SDK (generated by `build.rs`)
//!
//! **Alignment**: field names and serde annotations are byte-compatible
//! with `ir-runtime/src/types.rs` so `.agent.json` round-trips correctly.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Transparent wrapper around `serde_json::Value` that implements `ts_rs::TS`
/// mapping natively to TypeScript's `any` and Python's `Any`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, Default)]
#[serde(transparent)]

pub struct JsonValue(#[schemars(schema_with = "any_schema")] pub serde_json::Value);

fn any_schema(_gen: &mut schemars::gen::SchemaGenerator) -> schemars::schema::Schema {
    schemars::schema::Schema::Bool(true) // Accept anything
}

// ── Top-Level Agent IR ───────────────────────────────────────────────────────

/// Root IR for a compiled `.agent` file. Mirrors `ir-runtime/src/types.rs::AgentIR`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, Default)]
#[serde(rename_all = "camelCase")]
pub struct AgentIR {
    pub name: String,
    #[serde(default)]
    pub model_config: Vec<ModelConfigBlockIR>,
    #[serde(default)]
    pub input: Option<JsonValue>,
    #[serde(default)]
    pub output: Option<JsonValue>,
    #[serde(default)]
    pub context: Option<JsonValue>,
    #[serde(default)]
    pub tools: Vec<ToolIR>,
    #[serde(default)]
    pub workflows: Vec<WorkflowIR>,
    #[serde(default)]
    pub helpers: Vec<HelperIR>,
    #[serde(default)]
    pub types: Option<HashMap<String, TypeDeclIR>>,
    /// Tool grants per helper: `"all"` or `["toolA", "toolB"]`.
    #[serde(default)]
    pub helper_tool_grants: Option<HashMap<String, JsonValue>>,
    /// Handoff string per helper: `"user"` | `"thenContinue"` | absent → Return.
    #[serde(default)]
    pub helper_handoff: Option<HashMap<String, String>>,
    #[serde(default)]
    pub tests: Vec<JsonValue>,
    /// Lifecycle config (maxTokens, maxMessages, etc.).
    #[serde(default)]
    pub lifecycle: Option<JsonValue>,
    /// Custom intent declarations for this agent.
    #[serde(default)]
    pub custom_intents: Option<Vec<CustomIntentIR>>,
}

// ── Helper IR ────────────────────────────────────────────────────────────────

/// Mirrors `ir-runtime/src/types.rs::Helper`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(rename_all = "camelCase")]

pub struct HelperIR {
    pub name: String,
    pub description: Option<String>,
    #[serde(default)]
    pub model_config: Vec<ModelConfigBlockIR>,
    #[serde(default)]
    pub input: Option<JsonValue>,
    #[serde(default)]
    pub output: Option<JsonValue>,
    #[serde(default)]
    pub context: Option<JsonValue>,
    #[serde(default)]
    pub tools: Vec<ToolIR>,
    #[serde(default)]
    pub workflows: Vec<WorkflowIR>,
    #[serde(default)]
    pub custom_intents: Option<Vec<CustomIntentIR>>,
    #[serde(default)]
    pub examples: Vec<JsonValue>,
}

// ── Workflow IR ──────────────────────────────────────────────────────────────

/// Mirrors `ir-runtime/src/types.rs::Workflow`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
pub struct WorkflowIR {
    /// Serialized as `flowName`.
    #[serde(rename = "flowName")]
    pub name: String,
    /// Serialized as `flowParams`.
    #[serde(rename = "flowParams", default)]
    pub params: JsonValue,
    pub returns: JsonValue,
    pub description: Option<String>,
    #[serde(default)]
    pub body: Vec<ExpressionIR>,
    #[serde(default)]
    pub tools: Vec<ToolIR>,
    #[serde(default)]
    pub examples: Vec<JsonValue>,
}

// ── Tool IR ──────────────────────────────────────────────────────────────────

/// Mirrors `ir-runtime/src/types.rs::Tool`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
pub struct ToolIR {
    pub name: String,
    pub description: Option<String>,
    /// Parameter map: param name → type field JSON.
    pub params: JsonValue,
    pub returns: JsonValue,
    #[serde(default)]
    pub examples: Vec<JsonValue>,
}

// ── Type Declaration IR ──────────────────────────────────────────────────────

/// Mirrors `ir-runtime/src/types.rs::TypeDefinition`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct TypeDeclIR {
    pub is_output: bool,
    pub properties: HashMap<String, TypePropertyIR>,
}

/// Mirrors `ir-runtime/src/types.rs::TypeProperty`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(rename_all = "camelCase")]

pub struct TypePropertyIR {
    #[serde(rename = "type")]
    pub type_value: JsonValue,
    pub optional: bool,
    #[serde(default)]
    pub description: Option<String>,
}

// ── Expression IR ────────────────────────────────────────────────────────────

/// Tagged expression union. Mirrors `ir-runtime/src/types.rs::Expression`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(tag = "type", rename_all = "camelCase")]

pub enum ExpressionIR {
    // Literals
    #[serde(rename = "literal")]
    Literal { value: JsonValue },

    // Variables & Access
    #[serde(rename = "varRef")]
    VarRef { value: String },
    #[serde(rename = "memberAccess")]
    MemberAccess {
        object: Box<ExpressionIR>,
        properties: Vec<String>,
    },
    #[serde(rename = "indexAccess")]
    IndexAccess {
        object: String,
        index: Box<ExpressionIR>,
    },
    /// Sequence of expression parts (prompt building).
    #[serde(rename = "parts")]
    Parts { value: Vec<ExpressionIR> },
    /// Template string with `{{var}}` segments.
    #[serde(rename = "template")]
    Template { value: Vec<JsonValue> },
    /// Inline object literal `{ key: value, ... }`.
    #[serde(rename = "object")]
    Object {
        value: HashMap<String, ExpressionIR>,
    },
    /// Array literal.
    #[serde(rename = "array")]
    Array { value: Vec<ExpressionIR> },

    // Prompt
    #[serde(rename = "inlinePrompt")]
    InlinePrompt { parts: Vec<JsonValue> },
    #[serde(rename = "promptRef")]
    PromptRef {
        name: String,
        params: Vec<String>,
        args: Vec<ExpressionIR>,
        value: Vec<JsonValue>,
    },
    #[serde(rename = "promptExamples")]
    PromptExamples { examples: Vec<ExamplePairIR> },
    #[serde(rename = "schemaDirective")]
    SchemaDirective { path: String },

    // Conditional (inline template)
    #[serde(rename = "inlineIf")]
    InlineIf {
        condition: JsonValue,
        then: Vec<ExpressionIR>,
        #[serde(rename = "else", default)]
        else_block: Vec<ExpressionIR>,
    },

    // Statements in workflow body
    #[serde(rename = "if")]
    If {
        condition: JsonValue,
        then: Vec<ExpressionIR>,
        #[serde(rename = "else", default)]
        else_block: Vec<ExpressionIR>,
    },
    #[serde(rename = "return")]
    Return { value: Box<ExpressionIR> },
    #[serde(rename = "variableDeclaration")]
    VariableDeclaration {
        name: String,
        value: Box<ExpressionIR>,
    },
    #[serde(rename = "assign")]
    Assign {
        variable: String,
        value: Box<ExpressionIR>,
    },
    #[serde(rename = "parallel")]
    Parallel { body: Vec<ExpressionIR> },
    /// Transfer to a helper: `{ type: "transfer", target: <ExpressionIR>, mode: "..." }`.
    #[serde(rename = "transfer")]
    Transfer {
        target: Box<ExpressionIR>,
        mode: String,
    },

    // Calls
    #[serde(rename = "functionCall")]
    FunctionCall {
        value: String,
        args: Vec<ExpressionIR>,
    },
    #[serde(rename = "helperCall")]
    HelperCall {
        value: String,
        args: Vec<ExpressionIR>,
    },
    #[serde(rename = "promptCall")]
    PromptCall {
        value: String,
        args: Vec<ExpressionIR>,
    },

    // Context
    #[serde(rename = "contextRef")]
    ContextRef { property: String },

    // Binary Ops
    #[serde(rename = "binaryOp")]
    BinaryOp {
        left: Box<ExpressionIR>,
        op: String,
        right: Box<ExpressionIR>,
    },

    /// Wraps another expression (passthrough).
    #[serde(rename = "expression")]
    Expression { value: Box<ExpressionIR> },
}

/// Prompt conversation example pair. Mirrors `ir-runtime::ExamplePair`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct ExamplePairIR {
    pub user: String,
    pub assistant: String,
}

// ── Model Config IR ──────────────────────────────────────────────────────────

/// Mirrors `ir-runtime::ModelConfigEntry`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct ModelConfigBlockIR {
    #[serde(rename = "defaultConfig")]
    pub default_config: Option<ModelConfigIR>,
    #[serde(rename = "namedConfig", default)]
    pub named_config: Option<Vec<NamedModelConfigIR>>,
}

/// Mirrors `ir-runtime::NamedModelConfig`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct NamedModelConfigIR {
    #[serde(rename = "configName")]
    pub config_name: String,
    #[serde(flatten)]
    pub config: ModelConfigIR,
}

/// Mirrors `ir-runtime::ModelConfig`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct ModelConfigIR {
    pub model: ModelProviderIR,
    pub embedding: Option<ModelProviderIR>,
    pub prompt: JsonValue,
}

/// Mirrors `ir-runtime::ModelProvider`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(tag = "type", rename_all = "camelCase")]

pub enum ModelProviderIR {
    #[serde(rename = "gemini")]
    Gemini {
        #[serde(rename = "modelName")]
        model_name: String,
        config: Option<Box<JsonValue>>,
    },
    #[serde(rename = "openai")]
    OpenAI {
        #[serde(rename = "modelName")]
        model_name: String,
        config: Option<Box<JsonValue>>,
    },
    #[serde(rename = "custom")]
    Custom {
        id: String,
        url: String,
        #[serde(rename = "modelName")]
        model_name: String,
        config: Option<Box<JsonValue>>,
    },
    #[serde(rename = "modelRef")]
    ModelRef { name: String },
}

// ── Intent IR ────────────────────────────────────────────────────────────────

/// Mirrors `ir-runtime::CustomIntentDef`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct CustomIntentIR {
    pub name: String,
    pub description: Option<String>,
    /// Intent fields as a property map JSON object.
    pub fields: JsonValue,
    #[serde(default)]
    pub examples: Vec<JsonValue>,
}

// ── Handoff ──────────────────────────────────────────────────────────────────

/// The three handoff modes a helper can operate in.
///
/// Serialized to/from the JSON `helperHandoff` map value:
/// - `Return` → absent (no entry in the map)
/// - `User` → `"user"`
/// - `ThenContinue` → `"thenContinue"`
///
/// Mirrors `ir-runtime/src/runtime/helper_runner.rs::HandoffMode`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, PartialEq, Default)]
#[serde(rename_all = "camelCase")]

pub enum HandoffKindIR {
    /// Helper result is returned silently to the parent agent (default).
    #[default]
    Return,
    /// Helper streams directly to the user; parent stops afterwards.
    User,
    /// Helper streams directly to the user; parent continues afterwards.
    ThenContinue,
}

impl HandoffKindIR {
    /// Parse from the string stored in the `helperHandoff` map. Absent → `Return`.
    pub fn from_ir_str(s: Option<&str>) -> Self {
        match s {
            Some("user") => HandoffKindIR::User,
            Some("thenContinue") => HandoffKindIR::ThenContinue,
            _ => HandoffKindIR::Return,
        }
    }

    /// Serialize to the string stored in the `helperHandoff` map.
    /// `Return` produces `None` (no map entry).
    pub fn to_ir_str(&self) -> Option<&'static str> {
        match self {
            HandoffKindIR::User => Some("user"),
            HandoffKindIR::ThenContinue => Some("thenContinue"),
            HandoffKindIR::Return => None,
        }
    }
}

// ── Condition IR ─────────────────────────────────────────────────────────────

/// Mirrors `ir-runtime::Condition`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
#[serde(tag = "type", rename_all = "camelCase")]

pub enum ConditionIR {
    #[serde(rename = "comparison")]
    Comparison(ComparisonIR),
    #[serde(rename = "boolean")]
    Boolean { value: Box<ExpressionIR> },
    #[serde(rename = "contextRef")]
    ContextRef { property: String },
    #[serde(rename = "logical")]
    Logical {
        op: String,
        left: Box<ConditionIR>,
        right: Box<ConditionIR>,
    },
}

/// Mirrors `ir-runtime::Comparison`.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]

pub struct ComparisonIR {
    pub left: Box<ExpressionIR>,
    pub operator: String,
    pub right: Box<ExpressionIR>,
}
