[package]
name = "auwgent-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
auwgent-ast = { path = "../auwgent-ast" }
auwgent-errors = { path = "../auwgent-errors" }
auwgent-lexer = { path = "../auwgent-lexer" }
auwgent-parser = { path = "../auwgent-parser" }

[dev-dependencies]
auwgent-ir = { path = "../auwgent-ir" }
serde_json = { workspace = true }