use ir_runtime::{AgentIR, evaluator::Evaluator};
use serde_json::json;
use std::{collections::HashMap, fs};

/**
 * Main entry point for the IR Runtime verification harness.
 *
 * This file serves as a manual test runner to verify:
 * 1. JSON Parsing of the Agent IR
 * 2. Expression Evaluation (prompts, variables, templates)
 */
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // ======================================================================================
    // 1. Load and Parse IR
    // ======================================================================================

    // Read the JSON file generated by the CLI
    let content = fs::read_to_string("../manual-testing/out/main.agent.json")?;

    // Parse it into our strict AgentIR struct
    let agent: AgentIR = serde_json::from_str(&content)?;

    println!(" Successfully parsed Agent: {}", agent.name);

    // ======================================================================================
    // 2. Setup Runtime Environment
    // ======================================================================================

    // Initialize the Evaluator
    let evaluator = Evaluator::new(&agent);

    // Create the global scope (simulating runtime state)
    let mut scope = HashMap::new();

    // Define input data (simulating what a user would send to the agent)
    // In a real app, this comes from the request body
    let input_data = json!({
        "input": {
            "name": "World"
        },
        "context":{
            "isvip": false,
            "person": 1
        }
    });

    // Flatten the input object into the top-level scope
    // So "input.name" becomes accessible via scope.get("input") -> Object -> .get("name")
    if let Some(obj) = input_data.as_object() {
        for (k, v) in obj {
            scope.insert(k.clone(), v.clone());

            // FIX: Also expose context variables directly (e.g. "isvip")
            if k == "context" {
                if let Some(ctx_obj) = v.as_object() {
                    for (ck, cv) in ctx_obj {
                        scope.insert(ck.clone(), cv.clone());
                    }
                }
            }
        }
    }

    // ======================================================================================
    // 3. Execute & Verify
    // ======================================================================================

    // Evaluate the default model config's prompt
    if let Some(entry) = agent.model_config.first() {
        if let Some(default) = &entry.default_config {
            println!(" Evaluating prompt with scope: {:?}", scope);

            // Pass the populated scope to resolve variables like {{input.name}}
            let value = evaluator.evaluate(&default.prompt, &scope)?;

            println!("GENERATED PROMPT:");
            println!("---------------------------------------------------");
            if let Some(s) = value.as_str() {
                println!("{}", s);
            } else {
                println!("{}", value);
            }
            println!("---------------------------------------------------");
        }
    }

    // TODO: Add more checks here later (e.g. for tools, output schema)

    Ok(())
}
