schema_version = 1
id = "auwgent"
name = "Auwgent"
version = "0.1.0"
description = "Auwgent DSL support for Zed"
authors = ["Theophilus"]
repository = "https://github.com/snrraptopack/Auwgent"

[grammars.auwgent]
repository = "file://C:/Users/babyface/Desktop/auwgent/Auwgent/extension-zed/grammars/auwgent"
rev = "HEAD"

[language_servers.auwgent-lsp]
name = "Auwgent LSP"
languages = ["Auwgent"]
