//! Proc-macros for the Quew standard library.
//!
//! [`quew_builtin`] is the single source of truth for native builtin
//! functions. One Rust function annotation generates:
//! - a runtime `NativeRegistry` entry (via `inventory`)
//! - prelude metadata for build-script consumption
//!
//! Extension-method wrappers are generated by the prelude build script,
//! not by this macro.

use proc_macro::TokenStream;
use quote::quote;
use syn::parse::Parser;

/// Register a Rust function as a Quew native builtin.
///
/// ```ignore
/// #[quew_builtin(
///     id   = "std.string.len",
///     decl = r#"!@@function len(value: string): number"#,
/// )]
/// pub fn string_len(value: &str) -> usize {
///     value.len()
/// }
/// ```
///
/// Supported argument types: `&str`, `i64`, `f64`, `bool`, `&Value`.
/// Supported return types: `String`, `&str`, `i64`, `f64`, `bool`, `Value`,
/// and `Result<T, E>` for any of those `T`.
#[proc_macro_attribute]
pub fn quew_builtin(args: TokenStream, input: TokenStream) -> TokenStream {
    let args_span = proc_macro2::Span::call_site();

    // Parse attribute arguments as a punctuated list of name=value pairs.
    let mut id: Option<syn::LitStr> = None;
    let mut decl: Option<syn::LitStr> = None;
    let mut is_async = false;

    let parser = syn::punctuated::Punctuated::<syn::MetaNameValue, syn::Token![,]>::parse_terminated;
    let tokens = proc_macro2::TokenStream::from(args.clone());
    let pairs: syn::punctuated::Punctuated<syn::MetaNameValue, syn::Token![,]> =
        match parser.parse2(tokens) {
            Ok(p) => p,
            Err(e) => return e.to_compile_error().into(),
        };

    for nested in pairs {
        let key = nested
            .path
            .get_ident()
            .map(|i| i.to_string())
            .unwrap_or_default();
        match key.as_str() {
            "id" => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = nested.value
                {
                    id = Some(s);
                }
            }
            "decl" => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = nested.value
                {
                    decl = Some(s);
                }
            }
            "r#async" | "async" => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Bool(b),
                    ..
                }) = nested.value
                {
                    is_async = b.value;
                }
            }
            _ => {}
        }
    }

    let id = match id {
        Some(s) => s,
        None => {
            return syn::Error::new(args_span, "missing `id = \"...\"` attribute")
                .to_compile_error()
                .into();
        }
    };

    let _decl = match decl {
        Some(s) => s,
        None => {
            return syn::Error::new(args_span, "missing `decl = \"...\"` attribute")
                .to_compile_error()
                .into();
        }
    };

    // Parse the annotated function.
    let func = match syn::parse::<syn::ItemFn>(input.clone()) {
        Ok(f) => f,
        Err(e) => return e.to_compile_error().into(),
    };

    let func_name = &func.sig.ident;
    let func_vis = &func.vis;
    let func_block = &func.block;
    let func_sig = &func.sig;

    // Build wrapper that converts Value args to Rust types.
    let wrapper_name = syn::Ident::new(
        &format!("__quew_builtin_wrapper_{}", func_name),
        func_name.span(),
    );

    let arg_extractors: Vec<_> = func_sig
        .inputs
        .iter()
        .enumerate()
        .filter_map(|(idx, arg)| {
            if let syn::FnArg::Typed(t) = arg {
                Some(build_arg_extractor(idx, &t.ty, &t.pat))
            } else {
                None
            }
        })
        .collect();

    let arg_names: Vec<_> = func_sig
        .inputs
        .iter()
        .filter_map(|arg| {
            if let syn::FnArg::Typed(t) = arg {
                let pat = &t.pat;
                Some(quote!(#pat))
            } else {
                None
            }
        })
        .collect();

    let return_converter = build_return_converter(&func_sig.output, func_name);

    let id_lit = id.value();
    let id_tokens = quote!(#id_lit);

    if is_async {
        let expanded = quote! {
            #func_vis #func_sig #func_block

            compile_error!("async quew_builtin is not yet supported");
        };
        return expanded.into();
    }

    let expanded = quote! {
        #func_vis #func_sig #func_block

        #[doc(hidden)]
        #func_vis fn #wrapper_name(args: &[::quew_runtime::value::Value])
            -> Result<::quew_runtime::value::Value, ::quew_runtime::native::NativeError>
        {
            #(#arg_extractors)*
            let __result = #func_name(#(#arg_names),*);
            #return_converter
        }

        ::inventory::submit! {
            ::quew_runtime::native::NativeEntry {
                id: #id_tokens,
                handler: ::quew_runtime::native::NativeHandler::Sync(#wrapper_name),
            }
        }
    };

    expanded.into()
}

fn build_arg_extractor(idx: usize, ty: &syn::Type, pat: &syn::Pat) -> proc_macro2::TokenStream {
    let idx_lit = syn::Index::from(idx);
    let err_msg = format!("expected correct type for arg {}", idx);

    if is_type_str(ty) {
        quote! {
            let #pat = args.get(#idx_lit)
                .and_then(|v| v.as_str())
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    } else if is_type_i64(ty) {
        quote! {
            let #pat = args.get(#idx_lit)
                .and_then(|v| v.as_number())
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    } else if is_type_f64(ty) {
        quote! {
            let #pat = args.get(#idx_lit)
                .and_then(|v| v.as_float())
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    } else if is_type_bool(ty) {
        quote! {
            let #pat = args.get(#idx_lit)
                .and_then(|v| v.as_bool())
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    } else if is_type_value_ref(ty) {
        quote! {
            let #pat = args.get(#idx_lit)
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    } else {
        quote! {
            let #pat = args.get(#idx_lit)
                .ok_or_else(|| ::quew_runtime::native::NativeError::new(#err_msg))?;
        }
    }
}

fn build_return_converter(output: &syn::ReturnType, _func_name: &syn::Ident) -> proc_macro2::TokenStream {
    match output {
        syn::ReturnType::Default => quote! { Ok(::quew_runtime::value::Value::Null) },
        syn::ReturnType::Type(_, ty) => {
            if let Some(inner) = is_result_type(ty) {
                let t_converter = build_value_converter(inner);
                quote! {
                    match __result {
                        Ok(v) => { #t_converter }
                        Err(e) => Err(::quew_runtime::native::NativeError::new(format!("{}", e))),
                    }
                }
            } else {
                let converter = build_value_converter(ty);
                quote! {
                    let v = __result;
                    #converter
                }
            }
        }
    }
}

fn build_value_converter(ty: &syn::Type) -> proc_macro2::TokenStream {
    if is_type_string(ty) {
        quote! { Ok(::quew_runtime::value::Value::String(v)) }
    } else if is_type_str(ty) {
        quote! { Ok(::quew_runtime::value::Value::String(v.to_string())) }
    } else if is_type_i64(ty) {
        quote! { Ok(::quew_runtime::value::Value::Number(v)) }
    } else if is_type_f64(ty) {
        quote! { Ok(::quew_runtime::value::Value::Float(v)) }
    } else if is_type_bool(ty) {
        quote! { Ok(::quew_runtime::value::Value::Bool(v)) }
    } else if is_type_value(ty) {
        quote! { Ok(v) }
    } else {
        quote! { Ok(::quew_runtime::value::Value::Null) }
    }
}

// ── Type matching helpers ───────────────────────────────────────────────────

fn is_type_str(ty: &syn::Type) -> bool {
    if let syn::Type::Reference(r) = ty {
        if let syn::Type::Path(p) = r.elem.as_ref() {
            return path_is(p, "str");
        }
    }
    false
}

fn is_type_string(ty: &syn::Type) -> bool {
    if let syn::Type::Path(p) = ty {
        path_is(p, "String")
    } else {
        false
    }
}

fn is_type_i64(ty: &syn::Type) -> bool {
    if let syn::Type::Path(p) = ty {
        path_is(p, "i64")
    } else {
        false
    }
}

fn is_type_f64(ty: &syn::Type) -> bool {
    if let syn::Type::Path(p) = ty {
        path_is(p, "f64")
    } else {
        false
    }
}

fn is_type_bool(ty: &syn::Type) -> bool {
    if let syn::Type::Path(p) = ty {
        path_is(p, "bool")
    } else {
        false
    }
}

fn is_type_value(ty: &syn::Type) -> bool {
    if let syn::Type::Path(p) = ty {
        path_is(p, "Value")
    } else {
        false
    }
}

fn is_type_value_ref(ty: &syn::Type) -> bool {
    if let syn::Type::Reference(r) = ty {
        if let syn::Type::Path(p) = r.elem.as_ref() {
            return path_is(p, "Value");
        }
    }
    false
}

fn is_result_type(ty: &syn::Type) -> Option<&syn::Type> {
    if let syn::Type::Path(p) = ty {
        if let Some(seg) = p.path.segments.last() {
            if seg.ident == "Result" {
                if let syn::PathArguments::AngleBracketed(ref args) = seg.arguments {
                    if let Some(syn::GenericArgument::Type(inner)) = args.args.first() {
                        return Some(inner);
                    }
                }
            }
        }
    }
    None
}

fn path_is(p: &syn::TypePath, name: &str) -> bool {
    p.path.segments.len() == 1 && p.path.segments[0].ident == name
}
