name = "Auwgent"
grammar = "auwgent"
path_suffixes = ["agent"]
line_comments = ["// "]
language_servers = ["auwgent-lsp"]

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
