/**
 * @auwgent/runtime — Type-Safe TypeScript Wrapper
 *
 * This module provides a type-safe layer on top of the native Rust binding.
 * It extracts tool names from the IR JSON at the TYPE level, so TypeScript
 * will error if you forget to register any tool the agent needs.
 */

// ── Native binding (generated by napi-rs build) ──────────────────────────
import { Auwgent as AuwgentNative } from './index.js';

// Re-export the native class for advanced users who want raw access
export { AuwgentNative };

import {
    AuwgentToolError,
} from './types.js';

import type {
    AgentIRShape,
    ToolRegistry,
    ApiKeys,
    IRModelConfigEntry,
    ExtractToolNames,
    IRToolDef,
    IntentHandler,
    IntentHandlers,
    PartialIntentHandler,
    PartialIntentHandlers,
    SessionState
} from './types.js';

import type { Middleware, MiddlewareContext } from './middleware.js';

export * from './types.js';
export * from './middleware.js';


// ── Configuration ────────────────────────────────────────────────────────

export interface AuwgentConfig<IR extends AgentIRShape> {
    tools: ToolRegistry<IR>;
    middleware?: Middleware<IR>[];
    context?: Record<string, unknown>;
    apiKeys: ApiKeys<IR>;
}

// ── Type-Safe Auwgent Wrapper ────────────────────────────────────────────

export class TypedAuwgent<
    IR extends AgentIRShape,
    CustomIntents = never,
    Output = IR['output'] extends null ? any : IR['output'],
    Tools = ToolRegistry<IR>
> {
    private native: InstanceType<typeof AuwgentNative>;
    private ir: IR;
    private middleware: Middleware<IR, CustomIntents, Output, Tools>[];

    // ── Deferred intent handler storage ──
    // We store the user's handler here instead of immediately registering
    // it with the native binding. This allows us to register/deregister
    // the ThreadSafeFunction around each `run()` call, preventing the
    // N-API TSFN from keeping the Node.js event loop alive forever.
    private storedIntentHandler: IntentHandler<IR, CustomIntents, Output, Tools> | null = null;
    private storedPartialHandler: PartialIntentHandler<IR, CustomIntents, Output, Tools> | null = null;
    private lastTurnIntentValue: any = null;
    private lastTurnIntentName: string | null = null;
    private lastTurnRawBlock: string | undefined = undefined;
    private agentStack: string[] = [];

    constructor(ir: IR, config: AuwgentConfig<IR>) {
        this.ir = ir;
        this.middleware = (config.middleware as any) || [];
        this.native = new AuwgentNative(JSON.stringify(ir));

        if (config.context) {
            this.native.setContext(config.context);
        }

        const apiKeys = config.apiKeys as Record<string, string | undefined>;

        if (apiKeys?.geminiApiKey) {
            this.native.setGeminiDriver(apiKeys.geminiApiKey);
        }

        if (apiKeys?.openaiApiKey) {
            this.native.setOpenaiDriver(apiKeys.openaiApiKey);
        }

        // Register custom drivers from IR
        this.registerCustomDrivers(apiKeys);

        // Register all tools — guaranteed complete by the type system
        for (const [name, handler] of Object.entries(config.tools)) {
            this.native.registerTool(name, handler as (args: any) => Promise<any>);
        }
    }

    private registerCustomDrivers(apiKeys: Record<string, string | undefined>) {
        const collectFromEntry = (entry: any) => {
            if (entry.defaultConfig?.model?.type === 'custom') {
                const { id, url } = entry.defaultConfig.model;
                if (id && url) {
                    const key = apiKeys[`${id.replace(/-/g, '_')}ApiKey`];
                    if (key) {
                        this.native.setCustomDriver(id, key, url);
                    }
                }
            }
            if (entry.namedConfig) {
                for (const named of entry.namedConfig) {
                    if (named.model?.type === 'custom') {
                        const { id, url } = named.model;
                        if (id && url) {
                            const key = apiKeys[`${id.replace(/-/g, '_')}ApiKey`];
                            if (key) {
                                this.native.setCustomDriver(id, key, url);
                            }
                        }
                    }
                }
            }
        };

        if (this.ir.modelConfig) {
            for (const entry of this.ir.modelConfig) {
                collectFromEntry(entry);
            }
        }
        if (this.ir.helpers) {
            for (const helper of this.ir.helpers) {
                if (helper.modelConfig) {
                    for (const entry of helper.modelConfig) {
                        collectFromEntry(entry);
                    }
                }
            }
        }
    }

    /**
     * Register an intent callback for real-time streaming events.
     * The handler is stored and automatically registered/deregistered
     * around each `run()` call so the process can exit cleanly.
     */
    onIntent(handler: IntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedIntentHandler = handler;
    }

    /**
     * Register multiple intent handlers using an object-style API.
     */
    onHandlers(handlers: IntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntent(async (...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) return await (h as any)(value);
        });
    }

    /**
     * Register a partial intent callback for streaming updates.
     */
    onIntentPartial(handler: PartialIntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedPartialHandler = handler;
    }

    onHandlersPartial(handlers: PartialIntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntentPartial((...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) (h as any)(value);
        });
    }

    // Shared context storage for cross-hook state mapping
    private sharedContext: Record<string, any> = {};

    private getBuildContext(): MiddlewareContext<IR> {
        const activeAgent = this.agentStack[this.agentStack.length - 1] ?? this.ir.name;
        return {
            activeAgent: activeAgent as any,
            stack: [...this.agentStack],
            rootAgent: this.ir.name,
            rawBlock: this.lastTurnRawBlock,
            ...this.sharedContext
        } as MiddlewareContext<IR>;
    }

    /**
     * Activate the native ThreadSafeFunction listeners just before run().
     * This binds the stored handlers (including middleware pipeline) to the
     * Rust engine. After run() completes, `deactivateListeners()` replaces
     * them with no-ops so the TSFN ref is released and Node can exit.
     */
    private activateListeners(): void {
        const userHandler = this.storedIntentHandler;

        // Always register an onIntent callback (even if user didn't provide one)
        // so middleware can still intercept intents.
        this.native.onIntent(async (name: string, value: any) => {
            const intentCtx = this.getBuildContext();

            // Extract _raw from Rust-injected field and move to ctx.rawBlock
            // This keeps intent values clean and typed for the user,
            // while making raw YAML available to middleware for logging/audit
            if (value && typeof value === 'object' && '_raw' in value) {
                intentCtx.rawBlock = value._raw;
                this.lastTurnRawBlock = value._raw;
                delete value._raw;
            }

            // Pipeline through middleware
            for (const m of this.getMiddleware(intentCtx)) {
                if (m.onIntent) {
                    try {
                        const control = await (m.onIntent as any)(name, value, intentCtx);
                        if (control !== undefined && control !== null) {
                            return control as any;
                        }
                    } catch (e) {
                        throw e;
                    }
                }
            }

            // Track last intent value for onLLMEnd
            this.lastTurnIntentValue = value;
            this.lastTurnIntentName = name;

            // Forward to user handler
            if (userHandler) {
                const result = await (userHandler as any)(name, value);

                // Unified Error Hook Bridge:
                // If this turn was a tool error, trigger the onError lifecycle hook.
                if (name === 'tool_error' && value && typeof value === 'object') {
                    const toolErr = new AuwgentToolError(value.tool || 'unknown', value.message || 'unknown');
                    for (const m of this.getMiddleware(intentCtx)) {
                        if (m.onError) {
                            await (m as any).onError(toolErr, undefined, intentCtx);
                        }
                    }
                }

                return result ?? null;
            }

            // Unified Error Hook Bridge (when no user handler is defined)
            if (name === 'tool_error' && value && typeof value === 'object') {
                const toolErr = new AuwgentToolError(value.tool || 'unknown', value.message || 'unknown');
                for (const m of this.getMiddleware(intentCtx)) {
                    if (m.onError) {
                        await (m as any).onError(toolErr, undefined, intentCtx);
                    }
                }
            }
        });

        // Register partial handler if provided
        if (this.storedPartialHandler) {
            const partialHandler = this.storedPartialHandler;
            this.native.onIntentPartial((name: string, value: any) => {
                (partialHandler as any)(name, value);
            });
        }

        // Register Sub-Engine Lifecycle Hooks
        this.native.onSubEngineStart(async (helperName: string, emptySessionJson: string) => {
            let session = JSON.parse(emptySessionJson) as SessionState;

            // Maintain execution stack
            this.agentStack.push(helperName);

            const ctx = this.getBuildContext();
            ctx.systemPrompt = session.systemPrompt;

            for (const m of this.getMiddleware(ctx)) {
                if (m.onRunStart) {
                    session = await (m as any).onRunStart(session, ctx);
                }
            }
            return JSON.stringify(session);
        });

        this.native.onSubEngineComplete(async (helperName: string, completedSessionJson: string) => {
            const session = JSON.parse(completedSessionJson) as SessionState;
            const ctx = this.getBuildContext();
            ctx.systemPrompt = session.systemPrompt;

            for (const m of this.getMiddleware(ctx)) {
                if (m.onRunComplete) {
                    await (m as any).onRunComplete(session, ctx);
                }
            }

            // Pop active helper
            this.agentStack.pop();
        });

        // Register LLM Lifecycle Hooks
        this.native.onLlmStart(async (promptJson: string, systemPrompt: string) => {
            const ctx = this.getBuildContext();
            ctx.systemPrompt = systemPrompt;
            this.lastTurnIntentValue = null;
            this.lastTurnIntentName = null;
            let currentPrompt = promptJson;
            for (const m of this.getMiddleware(ctx)) {
                if (m.onLLMStart) {
                    const modified = await (m as any).onLLMStart(currentPrompt, ctx);
                    if (typeof modified === "string") {
                        currentPrompt = modified;
                    }
                }
            }
            return currentPrompt;
        });

        this.native.onLlmEnd(async (responseString: string, systemPrompt: string) => {
            const ctx = this.getBuildContext();
            ctx.systemPrompt = systemPrompt;
            if (this.lastTurnIntentName === 'response_text' || this.lastTurnIntentName === 'response_schema') {
                for (const m of this.getMiddleware(ctx)) {
                    if (m.onLLMEnd) {
                        await (m.onLLMEnd as any)(this.lastTurnIntentValue || {}, ctx);
                    }
                }
            }
        });
    }

    /**
     * Replace the native listeners with no-ops to release the TSFN ref.
     * This allows the Node.js event loop to drain and the process to exit.
     */
    private deactivateListeners(): void {
        // Clear all native listeners to release TSFN references
        this.native.clearListeners();
    }

    /** Run the agentic loop. Returns the exported session state. */
    async run(input?: string): Promise<SessionState> {
        this.sharedContext = {}; // Clear context for new run
        this.agentStack = [this.ir.name]; // Initialize stack with root agent
        this.lastTurnRawBlock = undefined; // Reset raw block for new run
        let currentSession = this.exportSession();

        // Activation / ThreadSafeFunction binding
        this.activateListeners();

        const runtimeCtx = this.getBuildContext();

        try {
            // onRunStart Interception
            for (const m of this.getMiddleware(runtimeCtx)) {
                if (m.onRunStart) {
                    currentSession = await (m as any).onRunStart(currentSession, runtimeCtx);
                }
            }

            // Execute Native
            this.importSession(currentSession);
            const json = await this.native.run(input ?? null);
            currentSession = JSON.parse(json) as SessionState;

            // onRunComplete Interception
            for (const m of this.getMiddleware(runtimeCtx)) {
                if (m.onRunComplete) {
                    await (m as any).onRunComplete(currentSession, runtimeCtx);
                }
            }

            return currentSession;

        } catch (error) {
            let handled = false;
            for (const m of this.getMiddleware(runtimeCtx)) {
                if (m.onError) {
                    const shouldSwallow = await (m as any).onError(error as Error, currentSession, runtimeCtx);
                    if (shouldSwallow) {
                        handled = true;
                        break;
                    }
                }
            }
            if (!handled) {
                throw error;
            }
            return currentSession;
        } finally {
            // Deactivate listeners after run to release the TSFN ref
            // and allow the Node.js process to exit gracefully.
            this.deactivateListeners();
        }
    }

    /**
     * Filter middleware based on the 'target' field and current active agent.
     */
    private getMiddleware(ctx: MiddlewareContext<IR>) {
        return this.middleware.filter(m => {
            if (!m.target) return true;
            const targets = Array.isArray(m.target) ? m.target : [m.target];
            return targets.includes(ctx.activeAgent as any);
        });
    }

    /** Export session state for persistence. */
    exportSession(): SessionState {
        return JSON.parse(this.native.exportSession()) as SessionState;
    }

    /** Import a previously exported session state. */
    importSession(session: SessionState): void {
        this.native.importSession(JSON.stringify(session));
    }

    /** Clear the session (fresh conversation). */
    clearSession(): void {
        this.native.clearSession();
    }

    /** Generate the system prompt (debugging). */
    generatePrompt(): string {
        return this.native.generatePrompt();
    }

    /** Get tool names defined in the IR. */
    getToolNames(): ExtractToolNames<IR>[] {
        return this.native.getToolNames() as ExtractToolNames<IR>[];
    }

    /** Get tool schemas (for introspection). */
    getToolSchemas(): IRToolDef[] {
        return JSON.parse(this.native.getToolSchemas()) as IRToolDef[];
    }

    /** Access the raw native binding for advanced usage. */
    get raw(): InstanceType<typeof AuwgentNative> {
        return this.native;
    }
}

// ── Factory Function ─────────────────────────────────────────────────────

/**
 * Create a type-safe Auwgent agent from an IR object.
 */
export function createAuwgent<
    const IR extends AgentIRShape,
    CustomIntents = never,
    Output = any,
    Tools extends Record<string, any> = ToolRegistry<IR>
>(
    ir: IR,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function createAuwgentFromIRJson<
    const IR extends AgentIRShape,
    CustomIntents = never,
    Output = IR['output'] extends null ? any : IR['output'],
    Tools = ToolRegistry<IR>
>(
    irJson: string,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    const ir = JSON.parse(irJson) as IR;
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function parseIR<const IR extends AgentIRShape>(json: string): IR {
    return JSON.parse(json) as IR;
}
