/**
 * @auwgent/runtime — Type-Safe TypeScript Wrapper
 *
 * This module provides a type-safe layer on top of the native Rust binding.
 * It extracts tool names from the IR JSON at the TYPE level, so TypeScript
 * will error if you forget to register any tool the agent needs.
 */

// ── Native binding (generated by napi-rs build) ──────────────────────────
 //@ts-ignore
import { Auwgent as AuwgentNative } from './index.js';

// Re-export the native class for advanced users who want raw access
export { AuwgentNative };

import {
    AuwgentToolError,
    type AuwgentWarning,
    type AuwgentWarningSource,
} from './types.js';

import type {
    AgentIRShape,
    ToolRegistry,
    ApiKeys,
    IRModelConfigEntry,
    ExtractToolNames,
    IRToolDef,
    IntentHandler,
    IntentHandlers,
    PartialIntentHandler,
    PartialIntentHandlers,
    SessionState,
    ExtractHelperNames,
    CollectAllOutputs,
    RunMetadata,
    TurnMetadata
} from './types.js';

import type { Middleware, MiddlewareContext } from './middleware.js';

export * from './types.js';
export * from './middleware.js';


// ── Configuration ────────────────────────────────────────────────────────

export interface AuwgentConfig<IR extends AgentIRShape> {
    tools: ToolRegistry<IR>;
    middleware?: Middleware<IR>[];
    context?: Record<string, unknown>;
    apiKeys: ApiKeys<IR>;
}

// ── Type-Safe Auwgent Wrapper ────────────────────────────────────────────

export class TypedAuwgent<
    IR extends AgentIRShape,
    CustomIntents extends { name: string; value: any } = never,
    Output = CollectAllOutputs<IR>,
    Tools = ToolRegistry<IR>
> {
    private native: InstanceType<typeof AuwgentNative>;
    private ir: IR;
    private middleware: Middleware<IR, CustomIntents, Output, Tools>[];

    // ── Deferred intent handler storage ──
    // We store the user's handler here instead of immediately registering
    // it with the native binding. This allows us to register/deregister
    // the ThreadSafeFunction around each `run()` call, preventing the
    // N-API TSFN from keeping the Node.js event loop alive forever.
    private storedIntentHandler: IntentHandler<IR, CustomIntents, Output, Tools> | null = null;
    private storedPartialHandler: PartialIntentHandler<IR, CustomIntents, Output, Tools> | null = null;
    private lastTurnRawBlock: string | undefined = undefined;
    private agentStack: string[] = [];
    private helperSessions = new Map<string, SessionState>();
    private warnings: AuwgentWarning[] = [];
    private warningHandler: ((warning: AuwgentWarning) => void) | null = null;

    constructor(ir: IR, config: AuwgentConfig<IR>) {
        this.ir = ir;
        this.middleware = (config.middleware as any) || [];
        this.native = new AuwgentNative(JSON.stringify(ir));

        if (config.context) {
            this.native.setContext(config.context);
        }

        const apiKeys = config.apiKeys as Record<string, string | undefined>;

        if (apiKeys?.geminiApiKey) {
            this.native.setGeminiDriver(apiKeys.geminiApiKey);
        }

        if (apiKeys?.openaiApiKey) {
            this.native.setOpenaiDriver(apiKeys.openaiApiKey);
        }

        // Register custom drivers from IR
        this.registerCustomDrivers(apiKeys);

        // Register all tools — guaranteed complete by the type system
        if (config.tools) {
            for (const [name, handler] of Object.entries(config.tools)) {
                this.native.registerTool(name, handler as (args: any) => Promise<any>);
            }
        }
    }

    private registerCustomDrivers(apiKeys: Record<string, string | undefined>) {
        const collectFromEntry = (entry: any) => {
            if (entry.defaultConfig?.model?.type === 'custom') {
                const { id, url } = entry.defaultConfig.model;
                if (id && url) {
                    const key = apiKeys[`${id.replace(/-/g, '_')}ApiKey`];
                    if (key) {
                        this.native.setCustomDriver(id, key, url);
                    }
                }
            }
            if (entry.namedConfig) {
                for (const named of entry.namedConfig) {
                    if (named.model?.type === 'custom') {
                        const { id, url } = named.model;
                        if (id && url) {
                            const key = apiKeys[`${id.replace(/-/g, '_')}ApiKey`];
                            if (key) {
                                this.native.setCustomDriver(id, key, url);
                            }
                        }
                    }
                }
            }
        };

        if (this.ir.modelConfig) {
            for (const entry of this.ir.modelConfig) {
                collectFromEntry(entry);
            }
        }
        if (this.ir.helpers) {
            for (const helper of this.ir.helpers) {
                if (helper.modelConfig) {
                    for (const entry of helper.modelConfig) {
                        collectFromEntry(entry);
                    }
                }
            }
        }
    }

    /**
     * Register an intent callback for real-time streaming events.
     * The handler is stored and automatically registered/deregistered
     * around each `run()` call so the process can exit cleanly.
     */
    onIntent(handler: IntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedIntentHandler = handler;
    }

    /**
     * Register multiple intent handlers using an object-style API.
     */
    onHandlers(handlers: IntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntent(async (...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) return await (h as any)(value);
        });
    }

    /**
     * Register a partial intent callback for streaming updates.
     */
    onIntentPartial(handler: PartialIntentHandler<IR, CustomIntents, Output, Tools>): void {
        this.storedPartialHandler = handler;
    }

    onHandlersPartial(handlers: PartialIntentHandlers<IR, CustomIntents, Output, Tools>): void {
        this.onIntentPartial((...args: any[]) => {
            const [name, value] = args;
            const h = handlers[name as keyof typeof handlers];
            if (h) (h as any)(value);
        });
    }

    // Shared context storage for cross-hook state mapping
    private sharedContext: Record<string, any> = {};

    private persistMiddlewareContext(ctx: MiddlewareContext<IR>): void {
        const reserved = new Set([
            'activeAgent',
            'stack',
            'rootAgent',
            'rawBlock',
            'systemPrompt',
            'embed',
            'embedBatch',
            'setContext',
        ]);

        for (const [key, value] of Object.entries(ctx as Record<string, any>)) {
            if (!reserved.has(key)) {
                this.sharedContext[key] = value;
            }
        }
    }

    private getBuildContext(): MiddlewareContext<IR> {
        const activeAgent = this.agentStack[this.agentStack.length - 1] ?? this.ir.name;
        return {
            activeAgent: activeAgent as any,
            stack: [...this.agentStack],
            rootAgent: this.ir.name,
            rawBlock: this.lastTurnRawBlock,
            setContext: (data: any) => this.native.setContext(data),
            embed: async (text: string) => {
                try {
                    return await this.native.embed(text);
                } catch (e) {
                    await this.triggerError(e as Error);
                    throw e;
                }
            },
            embedBatch: async (texts: string[]) => {
                try {
                    return await this.native.embedBatch(texts);
                } catch (e) {
                    await this.triggerError(e as Error);
                    throw e;
                }
            },
            ...this.sharedContext
        } as MiddlewareContext<IR>;
    }

    private buildContextFromRuntimeEvent(event: any): MiddlewareContext<IR> {
        const ctx = this.getBuildContext();
        const runtimeCtx = event?.context;

        if (runtimeCtx && typeof runtimeCtx.activeAgent === 'string') {
            ctx.activeAgent = runtimeCtx.activeAgent as any;
        }
        if (runtimeCtx && Array.isArray(runtimeCtx.stack)) {
            ctx.stack = [...runtimeCtx.stack];
            this.agentStack = [...runtimeCtx.stack];
        }
        if (runtimeCtx && typeof runtimeCtx.rootAgent === 'string') {
            ctx.rootAgent = runtimeCtx.rootAgent;
        }
        if (runtimeCtx && typeof runtimeCtx.rawBlock === 'string') {
            ctx.rawBlock = runtimeCtx.rawBlock;
            this.lastTurnRawBlock = runtimeCtx.rawBlock;
        }
        if (runtimeCtx && typeof runtimeCtx.systemPrompt === 'string') {
            ctx.systemPrompt = runtimeCtx.systemPrompt;
        }

        return ctx;
    }

    private async handleMiddlewareEvent(eventJson: string): Promise<string | undefined> {
        try {
            const event = JSON.parse(eventJson);
            const ctx = this.buildContextFromRuntimeEvent(event);

            switch (event?.type) {
            case 'intent': {
                const value = event?.value && typeof event.value === 'object'
                    ? { ...event.value }
                    : event?.value;

                if (value && typeof value === 'object' && '_raw' in value) {
                    delete value._raw;
                }

                for (const m of this.getMiddleware(ctx)) {
                    if (m.onIntent) {
                        try {
                            const control = await (m.onIntent as any)(event.name, value, ctx);
                            if (control !== undefined && control !== null) {
                                return JSON.stringify(control);
                            }
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onIntent threw', error, ctx.activeAgent as string);
                        }
                    }
                }

                this.persistMiddlewareContext(ctx);

                return undefined;
            }
            case 'llm_start': {
                let currentPrompt = typeof event?.prompt === 'string' ? event.prompt : '';

                for (const m of this.getMiddleware(ctx)) {
                    if (m.onLLMStart) {
                        try {
                            const modified = await (m.onLLMStart as any)(currentPrompt, ctx);
                            if (typeof modified === 'string') {
                                currentPrompt = modified;
                            }
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onLLMStart threw', error, ctx.activeAgent as string);
                        }
                    }
                }

                this.persistMiddlewareContext(ctx);

                return JSON.stringify({
                    prompt: currentPrompt,
                    stack: ctx.stack,
                });
            }
            case 'llm_end': {
                for (const m of this.getMiddleware(ctx)) {
                    if (m.onLLMEnd) {
                        try {
                            await (m.onLLMEnd as any)(event.response ?? {}, ctx);
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onLLMEnd threw', error, ctx.activeAgent as string);
                        }
                    }
                }

                this.persistMiddlewareContext(ctx);

                return undefined;
            }
            case 'run_start': {
                let session = event.session as SessionState;

                for (const m of this.getMiddleware(ctx)) {
                    if (m.onRunStart) {
                        try {
                            session = await (m.onRunStart as any)(session, ctx);
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onRunStart threw', error, ctx.activeAgent as string);
                        }
                    }
                }

                if (ctx.stack.length > 0) {
                    session.stack = [...ctx.stack];
                    this.agentStack = [...ctx.stack];
                }

                this.persistMiddlewareContext(ctx);

                return JSON.stringify({ session });
            }
            case 'run_complete': {
                const session = event.session as SessionState;

                for (const m of this.getMiddleware(ctx)) {
                    if (m.onRunComplete) {
                        try {
                            await (m.onRunComplete as any)(session, ctx);
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onRunComplete threw', error, ctx.activeAgent as string);
                        }
                    }
                }

                this.persistMiddlewareContext(ctx);

                return undefined;
            }
            case 'error': {
                const errorPayload = event?.error ?? {};
                const error = errorPayload?.kind === 'tool_error'
                    ? new AuwgentToolError(errorPayload.tool || 'unknown', errorPayload.message || 'unknown')
                    : new Error(errorPayload.message || 'Unknown runtime error');
                const session = event?.session as SessionState | undefined;

                for (const m of this.getMiddleware(ctx)) {
                    if (m.onError) {
                        try {
                            const shouldSwallow = await (m.onError as any)(error, session, ctx);
                            if (shouldSwallow) {
                                this.persistMiddlewareContext(ctx);
                                return JSON.stringify({ swallow: true });
                            }
                        } catch (middlewareError) {
                            this.reportWarning('middleware', 'middleware onError threw', middlewareError, ctx.activeAgent as string);
                        }
                    }
                }

                this.persistMiddlewareContext(ctx);

                return undefined;
            }
            default:
                return undefined;
            }
        } catch (error) {
            this.reportWarning('onMiddlewareEvent', 'failed to handle middleware event', error);
            return undefined;
        }
    }

    private async triggerError(error: Error) {
        const ctx = this.getBuildContext();
        for (const m of this.getMiddleware(ctx)) {
            if (m.onError) {
                try {
                    await (m as any).onError(error, undefined, ctx);
                } catch (middlewareError) {
                    this.reportWarning('middleware', 'middleware onError handler threw', middlewareError);
                }
            }
        }

        this.persistMiddlewareContext(ctx);
    }

    private reportWarning(source: AuwgentWarningSource, message: string, error?: unknown, agentName?: string): void {
        const warning: AuwgentWarning = {
            timestamp: new Date().toISOString(),
            source,
            message,
            detail: error instanceof Error ? error.message : (error != null ? String(error) : undefined),
            agentName,
        };

        this.warnings.push(warning);

        try {
            this.warningHandler?.(warning);
        } catch {
            // Keep warning flow non-fatal.
        }

        const detailSuffix = warning.detail ? `: ${warning.detail}` : '';
        const agentSuffix = warning.agentName ? ` [agent=${warning.agentName}]` : '';
        //@ts-ignore
        console.warn(`[auwgent][${warning.source}]${agentSuffix} ${warning.message}${detailSuffix}`);
    }

    onWarning(handler: (warning: AuwgentWarning) => void): void {
        this.warningHandler = handler;
    }

    getWarnings(): AuwgentWarning[] {
        return [...this.warnings];
    }

    clearWarnings(): void {
        this.warnings = [];
    }

    /** Generate an embedding for the given text using the configured model */
    async embed(text: string): Promise<number[]> {
        try {
            return await this.native.embed(text);
        } catch (e) {
            await this.triggerError(e as Error);
            throw e;
        }
    }

    /** Generate embeddings for a batch of texts */
    async embedBatch(texts: string[]): Promise<number[][]> {
        try {
            return await this.native.embedBatch(texts);
        } catch (e) {
            await this.triggerError(e as Error);
            throw e;
        }
    }

    /**
     * Activate the native ThreadSafeFunction listeners just before run().
     * This binds the stored handlers (including middleware pipeline) to the
     * Rust engine. After run() completes, `deactivateListeners()` replaces
     * them with no-ops so the TSFN ref is released and Node can exit.
     */
    private activateListeners(): void {
        const userHandler = this.storedIntentHandler;

        this.native.onIntent(async (name: string, value: any, agentName: string) => {
            try {
                const intentCtx = this.getBuildContext();
                intentCtx.activeAgent = agentName as any;

                if (value && typeof value === 'object' && '_raw' in value) {
                    intentCtx.rawBlock = value._raw;
                    this.lastTurnRawBlock = value._raw;
                    delete value._raw;
                }

                if (userHandler) {
                    const result = await (userHandler as any)(name, value, agentName);
                    return result ?? null;
                }
            } catch (error) {
                this.reportWarning('onIntent', 'intent callback failed', error, agentName);
            }
        });

        const partialHandler = this.storedPartialHandler;
        this.native.onIntentPartial((name: string, value: any, agentName: string) => {
                const partialCtx = this.getBuildContext();
                partialCtx.activeAgent = agentName as any;

                if (partialHandler) {
                    try {
                        const maybePromise = (partialHandler as any)(name, value, agentName);
                        if (maybePromise && typeof maybePromise.then === 'function') {
                            (maybePromise as Promise<unknown>).catch((error: unknown) => {
                                this.reportWarning('onIntentPartial', 'partial intent async callback rejected', error, agentName);
                            });
                        }
                    } catch (error) {
                        this.reportWarning('onIntentPartial', 'partial intent callback failed', error, agentName);
                    }
                }

                for (const m of this.getMiddleware(partialCtx)) {
                    if (m.onIntentPartial) {
                        try {
                            const maybePromise = (m.onIntentPartial as any)(name, value, partialCtx);
                            if (maybePromise && typeof maybePromise.then === 'function') {
                                (maybePromise as Promise<unknown>).catch((error: unknown) => {
                                    this.reportWarning('middleware', 'middleware onIntentPartial threw', error, agentName);
                                });
                            }
                        } catch (error) {
                            this.reportWarning('middleware', 'middleware onIntentPartial threw', error, agentName);
                        }
                    }
                }

                this.persistMiddlewareContext(partialCtx);
            });
        this.native.onMiddlewareEvent(async (eventJson: string) => {
            try {
                return await this.handleMiddlewareEvent(eventJson);
            } catch (error) {
                this.reportWarning('onMiddlewareEvent', 'middleware event callback failed', error);
                return undefined;
            }
        });

        this.native.onSubEngineStart(async (helperName: string, emptySessionJson: string) => {
            try {
                const session = this.helperSessions.get(helperName) || (JSON.parse(emptySessionJson) as SessionState);
                if (session.stack) {
                    this.agentStack = [...session.stack];
                }
                return JSON.stringify(session);
            } catch (error) {
                this.reportWarning('onSubEngineStart', 'sub-engine start callback failed', error, helperName);
                return emptySessionJson;
            }
        });

        this.native.onSubEngineComplete(async (helperName: string, completedSessionJson: string) => {
            try {
                const session = JSON.parse(completedSessionJson) as SessionState;
                this.helperSessions.set(helperName, session);
                if (session.stack) {
                    this.agentStack = [...session.stack];
                }
            } catch (error) {
                this.reportWarning('onSubEngineComplete', 'sub-engine complete callback failed', error, helperName);
            }
        });
    }

    /**
     * Replace the native listeners with no-ops to release the TSFN ref.
     * This allows the Node.js event loop to drain and the process to exit.
     */
    private deactivateListeners(): void {
        // Clear all native listeners to release TSFN references
        this.native.clearListeners();
    }

    /** Run the agentic loop. Returns the exported session state. */
    async run(input?: string): Promise<SessionState> {
        this.sharedContext = {}; // Clear context for new run
        this.lastTurnRawBlock = undefined; // Reset raw block for new run

        // Activation / ThreadSafeFunction binding
        this.activateListeners();

        try {
            const json = await (this.native.run as any)(
                input ?? null,
                null
            );
            const currentSession = JSON.parse(json) as SessionState;

            // Sync the local stack back from the modified session
            if (currentSession.stack) {
                this.agentStack = [...currentSession.stack];
            }

            return currentSession;
        } catch (error) {
            this.reportWarning('run', 'native run failed', error);
            throw error;
        } finally {
            // Deactivate listeners after run to release the TSFN ref
            // and allow the Node.js process to exit gracefully.
            this.deactivateListeners();
        }
    }

    /**
     * Get the exact token usage and prompt/response telemetry from the last full run().
     */
    getMetadata(): RunMetadata {
        return JSON.parse(this.native.getMetadata());
    }

    /**
     * Filter middleware based on the 'target' field and current active agent.
     */
    private getMiddleware(ctx: MiddlewareContext<IR>) {
        return this.middleware.filter(m => {
            if (!m.target) return true;
            const targets = Array.isArray(m.target) ? m.target : [m.target];
            return targets.includes(ctx.activeAgent as any);
        });
    }

    /** Export session state for persistence. */
    exportSession(): SessionState {
        return JSON.parse(this.native.exportSession()) as SessionState;
    }

    /** Import a previously exported session state. */
    importSession(session: SessionState): void {
        this.native.importSession(JSON.stringify(session));
    }

    /** Clear the session (fresh conversation). */
    clearSession(): void {
        this.native.clearSession();
        this.helperSessions.clear();
    }

    /**
     * Generate a system prompt.
     * @param helperName - Optional name of a helper to generate the prompt for. If omitted, generates the main agent prompt.
     */
    generatePrompt<T extends ExtractHelperNames<IR> | undefined = undefined>(
        helperName?: T
    ): string {
        return this.native.generatePrompt(helperName as string);
    }

    /** Get tool names defined in the IR. */
    getToolNames(): ExtractToolNames<IR>[] {
        return this.native.getToolNames() as ExtractToolNames<IR>[];
    }

    /** Get tool schemas (for introspection). */
    getToolSchemas(): IRToolDef[] {
        return JSON.parse(this.native.getToolSchemas()) as IRToolDef[];
    }

    /** Access the raw native binding for advanced usage. */
    get raw(): InstanceType<typeof AuwgentNative> {
        return this.native;
    }
}

// ── Factory Function ─────────────────────────────────────────────────────

/**
 * Create a type-safe Auwgent agent from an IR object.
 */
export function createAuwgent<
    const IR extends AgentIRShape,
    CustomIntents extends { name: string; value: any } = never,
    Output = IR['output'] extends Record<string, any> ? IR['output'] : never,
    Tools extends Record<string, any> = ToolRegistry<IR>
>(
    ir: IR,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR, CustomIntents, Output, Tools>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function createAuwgentFromIRJson<
    const IR extends AgentIRShape,
    CustomIntents extends { name: string; value: any } = never,
    Output = IR['output'] extends Record<string, any> ? IR['output'] : never,
    Tools = ToolRegistry<IR>
>(
    irJson: string,
    config: Omit<AuwgentConfig<IR>, 'tools'> & { tools: Tools; middleware?: Middleware<IR, CustomIntents, Output, Tools>[] }
): TypedAuwgent<IR, CustomIntents, Output, Tools> {
    const ir = JSON.parse(irJson) as IR;
    return new TypedAuwgent<IR, CustomIntents, Output, Tools>(ir, config as any);
}

export function parseIR<const IR extends AgentIRShape>(json: string): IR {
    return JSON.parse(json) as IR;
}
