/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Auwgent {
  /**
   * Create an Auwgent engine from a JSON IR string.
   *
   * ```js
   * const agent = new Auwgent(fs.readFileSync('main.agent.json', 'utf8'));
   * ```
   */
  constructor(irJson: string)
  /** Set the Gemini driver with the given API key. */
  setGeminiDriver(apiKey: string): void
  /** Set the OpenAI driver with the given API key. */
  setOpenaiDriver(apiKey: string): void
  /** Set a custom OpenAI-compatible driver with a unique ID. */
  setCustomDriver(id: string, apiKey: string, baseUrl: string): void
  setContext(context: any): void
  /**
   * Register a tool by name. The callback receives a JSON args object
   * and must return a JSON result.
   *
   * ```js
   * agent.registerTool('search', async (args) => {
   *   const result = await search(args.query);
   *   return { results: result };
   * });
   * ```
   */
  registerTool(name: string, callback: (args: any) => Promise<any>): void
  /**
   * Register an intent callback for real-time streaming events.
   *
   * The callback fires for every detected intent during the agentic loop:
   * - `"tool_call"` — LLM requested a tool call (value: { type, args })
   * - `"tool_result"` — Tool finished (value: { name, result })
   * - `"response_text"` — LLM text response (value: { text })
   * - `"response_schema"` — LLM structured output
   * - `"workflow_call"` — LLM requested a workflow
   * - `"error"` — An error occurred
   *
   * Return value controls behavior:
   * - `undefined` / `null` → engine auto-executes (default)
   * - `{ skip: true }` → skip this tool/workflow call
   * - `{ result: value }` → use this result instead of executing
   *
   * ```js
   * agent.onIntent((name, value) => {
   *   console.log(`[${name}]`, value);
   * });
   * ```
   */
  onIntent(callback: (name: string, value: any) => any): void
  /**
   * Register a partial intent callback for streaming updates.
   *
   * This fires as YAML data streams in, BEFORE the intent block is
   * complete. Useful for streaming partial text or showing tool args
   * as they arrive. Observational only — no control/skip/override.
   *
   * ```js
   * agent.onIntentPartial((name, value) => {
   *   if (name === 'response_text') {
   *     process.stdout.write(value.text ?? '');
   *   }
   * });
   * ```
   */
  onIntentPartial(callback: (name: string, value: any) => void): void
  /** Hook for TypeScript to preload a helper session before sub_engine.run() */
  onSubEngineStart(callback: (helperName: string, emptySessionJson: string) => Promise<string | undefined>): void
  /** Hook for TypeScript to save a helper session after sub_engine.run() */
  onSubEngineComplete(callback: (helperName: string, completedSessionJson: string) => Promise<void>): void
  /** Hook for TypeScript to receive the prompt before LLM generation */
  onLlmStart(callback: (prompt: string, systemPrompt: string) => Promise<string | undefined>): void
  /** Hook for TypeScript to receive the unparsed response after LLM generation */
  onLlmEnd(callback: (responseString: string, systemPrompt: string) => Promise<void>): void
  /**
   * Run the agentic loop with the given input.
   * Returns the exported session state as JSON.
   *
   * ```js
   * const session = await agent.run('Hello, agent!');
   * ```
   */
  run(input?: string | undefined | null): Promise<string>
  /**
   * Export the current session state as a JSON string.
   * The host can persist this and restore it later with `importSession()`.
   */
  exportSession(): string
  /** Import a previously exported session state. */
  importSession(json: string): void
  /** Clear the session (start a fresh conversation). */
  clearSession(): void
  /** Generate the system prompt (useful for debugging). */
  generatePrompt(): string
  /**
   * Get all tool names defined in the IR.
   * Used by the TypeScript wrapper for type-safe tool registration.
   */
  getToolNames(): Array<string>
  /** Get tool schemas as JSON (for TypeScript type generation). */
  getToolSchemas(): string
  /** Write a chunk directly to the orchestrator (for simulation/testing). */
  writeChunk(chunk: string): void
  /** Finalize the LLM stream (for simulation/testing). */
  endStream(): string
  /** Process any pending intents (for simulation/testing). */
  processIntents(): Promise<string>
}
