[package]
name = "auwgent-compile"
version = "0.1.0"
edition = "2021"

[dependencies]
auwgent-analysis = { path = "../auwgent-analysis" }
auwgent-ast = { path = "../auwgent-ast" }
auwgent-checker = { path = "../auwgent-checker" }
auwgent-errors = { path = "../auwgent-errors" }
auwgent-ir = { path = "../auwgent-ir" }
auwgent-ir-schema = { path = "../auwgent-ir-schema" }
serde_json = { workspace = true }